function cfg = defaultAutotuningConfig()
% defaultAutotuningConfig Default configuration for the autotuning layer.
%
% The default scenario targets:
%   models/ATLmodel.mat
%   data/evaluation/processed/desktop_atl20_bss_v1/nominal/esc_bus_coreBattery_dataset.mat
%
% The default estimator list is intentionally small because BayesOpt can be
% expensive. Add more estimator names to cfg.scenarios(k).estimator_names
% when needed.

cfg = struct();

cfg.run_name = 'autotuning';

cfg.objective = struct( ...
    'metric', 'SocRmsePct', ...
    'failure_objective', 1e9);

cfg.bayesopt = struct( ...
    'max_objective_evals', 30, ...
    'num_seed_points', 8, ...
    'is_objective_deterministic', true, ...
    'acquisition_function_name', 'expected-improvement-plus', ...
    'use_parallel', false, ...
    'auto_start_parallel_pool', true, ...
    'parallel_pool_size', [], ...
    'cache_objective_evaluations', true, ...
    'show_waitbar', true, ...
    'verbose', 1);

cfg.output = struct( ...
    'save_results', true, ...
    'results_root', fullfile('autotuning', 'results'), ...
    'generate_best_benchmark_results', true, ...
    'save_estimator_result_files', true, ...
    'aggregate_results_file', '');

cfg.estimator_configs = defaultEstimatorConfigs();
cfg.scenarios = defaultScenario();
end

function estimator_cfgs = defaultEstimatorConfigs()
esc_defaults = struct( ...
    'process_noise_field', 'sigma_w_esc', ...
    'sensor_noise_field', 'sigma_v_esc', ...
    'process_noise_bounds', [1e-6 1e2], ...
    'sensor_noise_bounds', [1e-8 2e-1]);

estimator_cfgs = repmat(struct(), 11, 1);

names = { ...
    'ROM-EKF', ...
    'ESC-SPKF', ...
    'ESC-EKF', ...
    'EaEKF', ...
    'EacrSPKF', ...
    'EnacrSPKF', ...
    'EDUKF', ...
    'EsSPKF', ...
    'EbSPKF', ...
    'EBiSPKF', ...
    'Em7SPKF'};

for idx = 1:numel(names)
    estimator_cfgs(idx).name = names{idx};
    estimator_cfgs(idx).process_noise_field = esc_defaults.process_noise_field;
    estimator_cfgs(idx).sensor_noise_field = esc_defaults.sensor_noise_field;
    estimator_cfgs(idx).process_noise_bounds = esc_defaults.process_noise_bounds;
    estimator_cfgs(idx).sensor_noise_bounds = esc_defaults.sensor_noise_bounds;
end

estimator_cfgs(1).process_noise_field = 'sigma_w_ekf';
estimator_cfgs(1).sensor_noise_field = 'sigma_v_ekf';
end

function scenarios = defaultScenario()
scenario = struct();
scenario.name = 'atl_bss_esc';
scenario.estimator_names = {'ROM-EKF'};
scenario.datasetSpec = struct( ...
    'dataset_file', fullfile('data', 'evaluation', 'processed', 'desktop_atl20_bss_v1', 'nominal', 'esc_bus_coreBattery_dataset.mat'), ...
    'dataset_variable', 'dataset', ...
    'builder_fcn', 'BSSsimESCdata', ...
    'builder_cfg', struct( ...
        'model_file', fullfile('models', 'ATLmodel.mat'), ...
        'profile_file', fullfile('data', 'evaluation', 'raw', 'omtlife8ahc_hp', 'Bus_CoreBatteryData_Data.mat'), ...
        'tc', 25), ...
    'dataset_soc_field', 'soc_true', ...
    'metric_soc_field', 'soc_true', ...
    'metric_voltage_field', 'voltage_v', ...
    'reference_name', 'ESC reference', ...
    'voltage_name', 'ESC voltage', ...
    'title_prefix', 'ATL BSS');

scenario.modelSpec = struct( ...
    'esc_model_file', fullfile('models', 'ATLmodel.mat'), ...
    'rom_model_file', fullfile('models', 'ROM_ATL20_beta.mat'), ...
    'tc', 25, ...
    'chemistry_label', 'ATL', ...
    'require_rom_match', true);

scenario.estimatorSetSpecBase = struct( ...
    'registry_name', 'all', ...
    'allow_rom_skip', true, ...
    'soc0_percent', [], ...
    'tuning', struct());

scenario.objectiveFlags = struct( ...
    'SOCfigs', false, ...
    'Vfigs', false, ...
    'Biasfigs', false, ...
    'R0figs', false, ...
    'InnovationACFPACFfigs', false, ...
    'Summaryfigs', false, ...
    'Verbose', false, ...
    'SaveResults', false);

scenario.bestResultFlags = struct( ...
    'SOCfigs', false, ...
    'Vfigs', false, ...
    'Biasfigs', false, ...
    'R0figs', false, ...
    'InnovationACFPACFfigs', false, ...
    'Summaryfigs', false, ...
    'Verbose', false, ...
    'SaveResults', true, ...
    'results_file', '');

scenarios = scenario;
end
