repo_root = '';
repo_root_candidates = {pwd, fileparts(mfilename('fullpath'))};
for repo_root_idx = 1:numel(repo_root_candidates)
    repo_root_candidate = char(repo_root_candidates{repo_root_idx});
    while ~isempty(repo_root_candidate)
        if exist(fullfile(repo_root_candidate, 'data'), 'dir') == 7 && ...
                exist(fullfile(repo_root_candidate, 'models'), 'dir') == 7 && ...
                exist(fullfile(repo_root_candidate, 'Evaluation'), 'dir') == 7 && ...
                exist(fullfile(repo_root_candidate, 'utility'), 'dir') == 7
            repo_root = repo_root_candidate;
            break;
        end
        parent_dir = fileparts(repo_root_candidate);
        if isempty(parent_dir) || strcmp(parent_dir, repo_root_candidate)
            break;
        end
        repo_root_candidate = parent_dir;
    end
    if ~isempty(repo_root)
        break;
    end
end

if isempty(repo_root)
    error('run_atl20_p25_bundle:RepoRootNotFound', ...
        'Could not locate the repository root. Run the example from inside the repository.');
end

addpath(genpath(repo_root));
cd(repo_root);

% If you edited Evaluation/xKFeval.m or Evaluation/runBenchmark.m and want
% to run only the benchmark/noise-study sections separately, uncomment the
% next three lines before running section 4 or 5 so the client and workers
% reload the updated source files.
delete(gcp('nocreate'))
clear xKFeval
clear runBenchmark

bundle_estimator_names = { ...
    'ROM-EKF', ...
    'ESC-SPKF', ...
    'ESC-EKF', ...
    'EaEKF', ...
    'EacrSPKF', ...
    'EnacrSPKF', ...
    'EDUKF', ...
    'EsSPKF', ...
    'EbSPKF', ...
    'EBiSPKF', ...
    'Em7SPKF'};

bundle_name = 'atl20_p25_bundle';
suite_version = 'desktop_atl20_bss_v1';

% Heavy local-only outputs
autotuning_profile_file = fullfile( ...
    'autotuning', 'results', 'atl20_p25_bundle_autotuning_results.mat');
benchmark_results_file = fullfile( ...
    'Evaluation', 'results', 'atl20_p25_bundle_benchmark_results.mat');
noise_cov_results_file = fullfile( ...
    'Evaluation', 'NoiseTuningSweep', 'results', 'atl20_p25_bundle_noise_cov_study.mat');

% Lightweight trackable summaries
autotuning_summary_paths = BundleEvalHelpers.buildPromotedSummaryPaths('autotuning', suite_version, bundle_name);
benchmark_summary_paths = BundleEvalHelpers.buildPromotedSummaryPaths('evaluation', suite_version, bundle_name);
noise_cov_summary_paths = BundleEvalHelpers.buildPromotedSummaryPaths('evaluation', suite_version, [bundle_name '_noise_cov_study']);
tuned_params_file = BundleEvalHelpers.buildPromotedParamsPath(suite_version, bundle_name);
autotuning_summary_file = autotuning_summary_paths.json_file;
autotuning_summary_md_file = autotuning_summary_paths.markdown_file;
benchmark_summary_file = benchmark_summary_paths.json_file;
benchmark_summary_md_file = benchmark_summary_paths.markdown_file;
noise_cov_summary_file = noise_cov_summary_paths.json_file;
noise_cov_summary_md_file = noise_cov_summary_paths.markdown_file;

% Optional generated figures
save_summary_artifacts = true;
save_optional_figures = false;
figure_format = 'png';
evaluation_figure_root = fullfile('results', 'figures', 'evaluation', suite_version, bundle_name);
autotuning_figure_root = fullfile('results', 'figures', 'autotuning', suite_version, bundle_name);

%% 1) OCV identification: 25 degC only, Vavg engine
cfg_ocv = struct();
cfg_ocv.run_name = 'ATL20 OCV identification P25 only';
cfg_ocv.ocv_data_input = fullfile('data', 'modelling', 'processed', 'ocv', 'atl20');
cfg_ocv.data_prefix = 'ATL';
cfg_ocv.cell_id = 'ATL20';
cfg_ocv.engine = 'voltageAverage';
cfg_ocv.temperature_scope = 'single';
cfg_ocv.desired_temperature = 25;
cfg_ocv.min_v = 2.0;
cfg_ocv.max_v = 3.75;
cfg_ocv.save_plots = false;
cfg_ocv.debug_plots = false;
cfg_ocv.output = struct( ...
    'save_model', true, ...
    'save_results', true, ...
    'include_model_struct', false, ...
    'model_output_file', fullfile('data', 'modelling', 'derived', 'ocv_models', 'atl20', 'ATL20model-ocv-vavgFT.mat'), ...
    'results_file', fullfile('data', 'modelling', 'derived', 'identification_results', 'atl20', 'ATL20_ocv_identification_results.mat'));

ocv_results = runOcvIdentification(cfg_ocv); 

%% 2) Dynamic identification: full ESC model at 25 degC
close all;
cfg_dyn = struct();
cfg_dyn.run_name = 'ATL20 P25 ESC identification';
cfg_dyn.ocv_model_input = fullfile('data', 'modelling', 'derived', 'ocv_models', 'atl20', 'ATL20model-ocv-vavgFT.mat');
cfg_dyn.dynamic_input = fullfile('data', 'modelling', 'processed', 'dynamic', 'atl20');
cfg_dyn.desired_temperature = 25;
cfg_dyn.numpoles = 2;
cfg_dyn.do_hysteresis = true;
cfg_dyn.output = struct( ...
    'save_model', true, ...
    'save_results', true, ...
    'enabled_plots', false, ...
    'include_model_struct', false, ...
    'model_output_file', fullfile('models', 'ATL20model_P25.mat'), ...
    'results_file', fullfile('data', 'modelling', 'derived', 'identification_results', 'atl20', 'ATL20model_P25_identification_results.mat'));

dyn_results = runDynamicIdentification(cfg_dyn); %#ok<NASGU>

%% 2B) Application-dataset evaluation for ATL20model_P25 on the desktop ATL20 ESC case
step2b_repo_root = BundleEvalHelpers.resolveBundleRepoRoot();
addpath(genpath(step2b_repo_root));
step2b_model_file = fullfile(step2b_repo_root, 'models', 'ATL20model_P25.mat');
step2b_dataset_file = fullfile( ...
    step2b_repo_root, 'data', 'evaluation', 'processed', 'desktop_atl20_bss_v1', ...
    'nominal', 'esc_bus_coreBattery_dataset.mat');
step2b_validation_results_file = fullfile( ...
    step2b_repo_root, 'data', 'modelling', 'derived', 'validation_results', 'esc', ...
    'ATL20model_P25_desktop_atl20_bss_v1_validation.mat');
step2b_models_markdown_file = fullfile(step2b_repo_root, 'results', 'models.md');

atl20_p25_application_validation = ESCvalidation( ...
    step2b_model_file, step2b_dataset_file, false); %#ok<NASGU>

BundleEvalHelpers.ensureDir(fileparts(step2b_validation_results_file));
save(step2b_validation_results_file, 'atl20_p25_application_validation');
BundleEvalHelpers.upsertAtl20P25ModelValidationMarkdown( ...
    step2b_models_markdown_file, atl20_p25_application_validation, ...
    step2b_model_file, step2b_dataset_file, step2b_validation_results_file);

%% 3) Autotuning: all estimator-layer bundle estimators on the ATL20 P25 desktop case
cfg_auto = defaultAutotuningConfig();
cfg_auto.run_name = 'atl20_p25_bundle_autotuning';
cfg_auto.output.aggregate_results_file = autotuning_profile_file;
% Parallel BayesOpt requires MATLAB Parallel Computing Toolbox. If the
% toolbox or a local pool is unavailable, runAutotuning falls back to serial.
cfg_auto.bayesopt.use_parallel = true;

cfg_auto.scenarios = struct( ...
    'name', 'atl20_p25_bss_esc', ...
    'suite_version', 'desktop_atl20_bss_v1', ...
    'estimator_names', {bundle_estimator_names}, ...
    'datasetSpec', struct( ...
        'dataset_file', fullfile('data', 'evaluation', 'processed', 'desktop_atl20_bss_v1', 'nominal', 'esc_bus_coreBattery_dataset.mat'), ...
        'dataset_variable', 'dataset', ...
        'builder_fcn', 'BSSsimESCdata', ...
        'builder_cfg', struct( ...
            'model_file', fullfile('models', 'ATL20model_P25.mat'), ...
            'profile_file', fullfile('data', 'evaluation', 'raw', 'omtlife8ahc_hp', 'Bus_CoreBatteryData_Data.mat'), ...
            'tc', 25), ...
        'dataset_soc_field', 'soc_true', ...
        'metric_soc_field', 'soc_true', ...
        'metric_voltage_field', 'voltage_v', ...
        'reference_name', 'ESC reference', ...
        'voltage_name', 'ESC voltage', ...
        'title_prefix', 'ATL20 P25 BSS'), ...
    'modelSpec', struct( ...
        'esc_model_file', fullfile('models', 'ATL20model_P25.mat'), ...
        'rom_model_file', fullfile('models', 'ROM_ATL20_beta.mat'), ...
        'tc', 25, ...
        'chemistry_label', 'ATL20', ...
        'require_rom_match', true), ...
    'estimatorSetSpecBase', struct( ...
        'registry_name', 'all', ...
        'allow_rom_skip', true, ...
        'soc0_percent', [], ...
        'tuning', struct()), ...
    'objectiveFlags', struct( ...
        'SOCfigs', false, ...
        'Vfigs', false, ...
        'Biasfigs', false, ...
        'R0figs', false, ...
        'InnovationACFPACFfigs', false, ...
        'Summaryfigs', false, ...
        'Verbose', false, ...
        'SaveResults', false), ...
    'bestResultFlags', struct( ...
        'SOCfigs', false, ...
        'Vfigs', false, ...
        'Biasfigs', false, ...
        'R0figs', false, ...
        'InnovationACFPACFfigs', false, ...
        'Summaryfigs', false, ...
        'Verbose', false, ...
        'SaveResults', true, ...
        'results_file', ''));

autotuning_results = runAutotuning(cfg_auto);

if save_summary_artifacts
    autotuning_summary = BundleEvalHelpers.buildAutotuningSummaryArtifact( ...
        autotuning_results, autotuning_profile_file, autotuning_summary_file, ...
        autotuning_summary_md_file, suite_version, bundle_name);
    autotuning_tuned_params = BundleEvalHelpers.buildAutotuningTunedParamsArtifact( ...
        autotuning_results, autotuning_profile_file, tuned_params_file, ...
        suite_version, bundle_name);
    BundleEvalHelpers.writeJsonArtifact(autotuning_summary_file, autotuning_summary);
    BundleEvalHelpers.writeMarkdownArtifact(autotuning_summary_md_file, BundleEvalHelpers.renderAutotuningSummaryMarkdown(autotuning_summary));
    BundleEvalHelpers.writeJsonArtifact(tuned_params_file, autotuning_tuned_params);
end

if save_optional_figures
    autotuning_figures = plotAutotunedResults(autotuning_results);
    BundleEvalHelpers.exportFigureCollection(autotuning_figures, autotuning_figure_root, 'atl20_p25_bundle_autotuning', figure_format);
end

%% 4) Benchmark bundle validation with the new P25 ESC model and the tuned bundle
% This section is intentionally self-contained so it can be run by itself.
% Full per-estimator trajectories for this final tuned benchmark are saved
% into step4_benchmark_results_file through runBenchmark -> xKFeval.
step4_bundle_name = 'atl20_p25_bundle';
step4_suite_version = 'desktop_atl20_bss_v1';
step4_autotuning_profile_file = fullfile( ...
    'autotuning', 'results', 'atl20_p25_bundle_autotuning_results.mat');
step4_tuned_params_file = BundleEvalHelpers.buildPromotedParamsPath(step4_suite_version, step4_bundle_name);
step4_benchmark_results_file = fullfile( ...
    'Evaluation', 'results', 'atl20_p25_bundle_benchmark_results.mat');
step4_benchmark_summary_paths = BundleEvalHelpers.buildPromotedSummaryPaths( ...
    'evaluation', step4_suite_version, step4_bundle_name);
step4_benchmark_summary_file = step4_benchmark_summary_paths.json_file;
step4_benchmark_summary_md_file = step4_benchmark_summary_paths.markdown_file;
step4_save_summary_artifacts = true;
step4_save_optional_figures = false;
step4_figure_format = 'png';
step4_evaluation_figure_root = fullfile( ...
    'results', 'figures', 'evaluation', step4_suite_version, step4_bundle_name);
step4_tuning_spec = BundleEvalHelpers.resolveStep4TuningSpec( ...
    step4_autotuning_profile_file, step4_tuned_params_file, 'atl20_p25_bss_esc');
% Recovery-only rerender path, no benchmark rerun:
% writeBenchmarkPromotedSummary( ...
%     step4_benchmark_results_file, step4_benchmark_summary_file, ...
%     step4_benchmark_summary_md_file, step4_suite_version, ...
%     step4_bundle_name, step4_tuning_spec.param_file);

datasetSpec = struct( ...
    'dataset_file', fullfile('data', 'evaluation', 'processed', 'desktop_atl20_bss_v1', 'nominal', 'esc_bus_coreBattery_dataset.mat'), ...
    'dataset_variable', 'dataset');

modelSpec = struct( ...
    'esc_model_file', fullfile('models', 'ATL20model_P25.mat'), ...
    'rom_model_file', fullfile('models', 'ROM_ATL20_beta.mat'), ...
    'tc', 25, ...
    'chemistry_label', 'ATL20', ...
    'require_rom_match', true);

estimatorSetSpec = struct( ...
    'registry_name', 'mainEval10', ...
    'tuning', step4_tuning_spec);

flags = struct( ...
    'SOCfigs', false, ...
    'Vfigs', false, ...
    'Biasfigs', true, ...
    'R0figs', true, ...
    'InnovationACFPACFfigs', true, ...
    'Summaryfigs', true, ...
    'Verbose', true, ...
    'use_parallel', true, ...
    'SaveResults', true, ...
    'results_file', step4_benchmark_results_file);

bundle_results = runBenchmark(datasetSpec, modelSpec, estimatorSetSpec, flags);

if step4_save_summary_artifacts
    writeBenchmarkPromotedSummary( ...
        step4_benchmark_results_file, step4_benchmark_summary_file, ...
        step4_benchmark_summary_md_file, step4_suite_version, ...
        step4_bundle_name, step4_tuning_spec.param_file);
end

if step4_save_optional_figures
    benchmark_figures = plotEvalResults(bundle_results);
    BundleEvalHelpers.exportFigureCollection( ...
        benchmark_figures, step4_evaluation_figure_root, ...
        'atl20_p25_bundle_benchmark', step4_figure_format);
end

%% 5A) Full grid noise-covariance sweep on the ATL20 P25 bundle, group 1
% This section is self-contained. If you run only this section after
% editing xKFeval.m or runBenchmark.m, use the optional reload block at the
% top of the script first.
step5a_bundle_name = 'atl20_p25_bundle_noise_cov_study_group1';
step5a_suite_version = 'desktop_atl20_bss_v1';
step5a_repo_root = BundleEvalHelpers.resolveBundleRepoRoot();
step5a_bundle_estimator_names = { ...
    'ROM-EKF', ...
    'ESC-SPKF', ...
    'ESC-EKF', ...
    'EaEKF', ...
    'EacrSPKF', ...
    'EnacrSPKF'};
step5a_noise_results_file = fullfile( ...
    step5a_repo_root, 'Evaluation', 'NoiseTuningSweep', 'results', 'atl20_p25_bundle_noise_cov_study_group1.mat');
step5a_noise_summary_paths = BundleEvalHelpers.buildPromotedSummaryPaths( ...
    'evaluation', step5a_suite_version, step5a_bundle_name);
step5a_noise_summary_file = fullfile(step5a_repo_root, step5a_noise_summary_paths.json_file);
step5a_noise_summary_md_file = fullfile(step5a_repo_root, step5a_noise_summary_paths.markdown_file);
step5a_save_summary_artifacts = true;
% Recovery-only rerender path, no sweep rerun:
% writeNoiseSweepSummaryArtifacts( ...
%     step5a_noise_results_file, step5a_noise_summary_file, ...
%     step5a_noise_summary_md_file, step5a_suite_version, step5a_bundle_name);
step5a_noise_cfg = BundleEvalHelpers.buildStep5NoiseSweepConfig( ...
    step5a_bundle_estimator_names, step5a_noise_results_file);
noise_cov_results_group1 = runNoiseCovStudy([], [], [], step5a_noise_cfg); %#ok<NASGU>

if step5a_save_summary_artifacts
    BundleEvalHelpers.writeNoiseSweepSummaryArtifacts( ...
        step5a_noise_results_file, step5a_noise_summary_file, ...
        step5a_noise_summary_md_file, step5a_suite_version, step5a_bundle_name);
end

%% 5B) Full grid noise-covariance sweep on the ATL20 P25 bundle, group 2
% This section is self-contained. If you run only this section after
% editing xKFeval.m or runBenchmark.m, use the optional reload block at the
% top of the script first.
step5b_bundle_name = 'atl20_p25_bundle_noise_cov_study_group2';
step5b_suite_version = 'desktop_atl20_bss_v1';
step5b_repo_root = BundleEvalHelpers.resolveBundleRepoRoot();
step5b_bundle_estimator_names = { ...
    'EDUKF', ...
    'EsSPKF', ...
    'EbSPKF', ...
    'EBiSPKF', ...
    'Em7SPKF'};
step5b_noise_results_file = fullfile( ...
    step5b_repo_root, 'Evaluation', 'NoiseTuningSweep', 'results', 'atl20_p25_bundle_noise_cov_study_group2.mat');
step5b_noise_summary_paths = BundleEvalHelpers.buildPromotedSummaryPaths( ...
    'evaluation', step5b_suite_version, step5b_bundle_name);
step5b_noise_summary_file = fullfile(step5b_repo_root, step5b_noise_summary_paths.json_file);
step5b_noise_summary_md_file = fullfile(step5b_repo_root, step5b_noise_summary_paths.markdown_file);
step5b_save_summary_artifacts = true;
% Recovery-only rerender path, no sweep rerun:
% writeNoiseSweepSummaryArtifacts( ...
%     step5b_noise_results_file, step5b_noise_summary_file, ...
%     step5b_noise_summary_md_file, step5b_suite_version, step5b_bundle_name);
step5b_noise_cfg = BundleEvalHelpers.buildStep5NoiseSweepConfig( ...
    step5b_bundle_estimator_names, step5b_noise_results_file);
noise_cov_results_group2 = runNoiseCovStudy([], [], [], step5b_noise_cfg); %#ok<NASGU>

if step5b_save_summary_artifacts
    BundleEvalHelpers.writeNoiseSweepSummaryArtifacts( ...
        step5b_noise_results_file, step5b_noise_summary_file, ...
        step5b_noise_summary_md_file, step5b_suite_version, step5b_bundle_name);
end

%% 6) Initial-SOC sweep on the ATL20 P25 bundle for all estimators
% This section is self-contained. If you run only this section after
% editing xKFeval.m or runBenchmark.m, use the optional reload block at the
% top of the script first.
step6_bundle_name = 'atl20_p25_bundle_init_soc_sweep';
step6_suite_version = 'desktop_atl20_bss_v1';
step6_repo_root = BundleEvalHelpers.resolveBundleRepoRoot();
step6_bundle_estimator_names = { ...
    'ROM-EKF', ...
    'ESC-SPKF', ...
    'ESC-EKF', ...
    'EaEKF', ...
    'EacrSPKF', ...
    'EnacrSPKF', ...
    'EDUKF', ...
    'EsSPKF', ...
    'EbSPKF', ...
    'EBiSPKF', ...
    'Em7SPKF'};
step6_autotuning_profile_file = fullfile( ...
    step6_repo_root, 'autotuning', 'results', 'atl20_p25_bundle_autotuning_results.mat');
step6_tuned_params_file = fullfile( ...
    step6_repo_root, BundleEvalHelpers.buildPromotedParamsPath(step6_suite_version, 'atl20_p25_bundle'));
step6_init_soc_results_file = fullfile( ...
    step6_repo_root, 'Evaluation', 'initSOCs', 'results', ...
    'atl20_p25_bundle_init_soc_sweep.mat');
step6_init_soc_summary_file = fullfile( ...
    step6_repo_root, 'Evaluation', 'initSOCs', 'results', ...
    'atl20_p25_bundle_init_soc_sweep_summary.mat');
step6_init_soc_summary_paths = BundleEvalHelpers.buildPromotedSummaryPaths( ...
    'evaluation', step6_suite_version, step6_bundle_name);
step6_init_soc_summary_json_file = fullfile( ...
    step6_repo_root, step6_init_soc_summary_paths.json_file);
step6_init_soc_summary_md_file = fullfile( ...
    step6_repo_root, step6_init_soc_summary_paths.markdown_file);
step6_save_summary_artifacts = true;
step6_tuning_spec = BundleEvalHelpers.resolveStep4TuningSpec( ...
    step6_autotuning_profile_file, step6_tuned_params_file, 'atl20_p25_bss_esc');
% Recovery-only re-summary path, no sweep rerun:
% writeInitSocPromotedSummary( ...
%     step6_init_soc_results_file, step6_init_soc_summary_file, ...
%     step6_init_soc_summary_json_file, step6_init_soc_summary_md_file, ...
%     step6_suite_version, step6_bundle_name);
step6_cfg = BundleEvalHelpers.buildStep6InitSocSweepConfig( ...
    step6_bundle_estimator_names, step6_init_soc_results_file, step6_tuning_spec);
step6_soc_range_percent = [0 100];
step6_soc_step_percent = 5;

init_soc_sweep_results = sweepInitSocStudy( ... %#ok<NASGU>
    step6_soc_range_percent, step6_soc_step_percent, step6_cfg);
step6_summary = extractInitSocSweepResults( ...
    step6_init_soc_results_file, ...
    struct('display_tables', false, 'save_summary', true, ...
    'summary_file', step6_init_soc_summary_file)); %#ok<NASGU>
printInitSocSweepSummary(step6_summary);
if step6_save_summary_artifacts
    writeInitSocPromotedSummary( ...
        step6_init_soc_results_file, step6_init_soc_summary_file, ...
        step6_init_soc_summary_json_file, step6_init_soc_summary_md_file, ...
        step6_suite_version, step6_bundle_name);
end

%% 7) Injection study on canonical additive, fault, and hall-bias cases
% This section is self-contained. If you run only this section after
% editing xKFeval.m or runBenchmark.m, use the optional reload block at the
% top of the script first.
% Injection cases are defined inline below, so this section does not rely
% on pre-generated derived-case manifests.
step7_repo_root = '';
step7_repo_root_candidates = {pwd, fileparts(mfilename('fullpath'))};
for step7_repo_root_idx = 1:numel(step7_repo_root_candidates)
    step7_repo_root_candidate = char(step7_repo_root_candidates{step7_repo_root_idx});
    while ~isempty(step7_repo_root_candidate)
        if exist(fullfile(step7_repo_root_candidate, 'data'), 'dir') == 7 && ...
                exist(fullfile(step7_repo_root_candidate, 'models'), 'dir') == 7 && ...
                exist(fullfile(step7_repo_root_candidate, 'Evaluation'), 'dir') == 7 && ...
                exist(fullfile(step7_repo_root_candidate, 'utility'), 'dir') == 7
            step7_repo_root = step7_repo_root_candidate;
            break;
        end
        step7_parent_dir = fileparts(step7_repo_root_candidate);
        if isempty(step7_parent_dir) || strcmp(step7_parent_dir, step7_repo_root_candidate)
            break;
        end
        step7_repo_root_candidate = step7_parent_dir;
    end
    if ~isempty(step7_repo_root)
        break;
    end
end

if isempty(step7_repo_root)
    error('run_atl20_p25_bundle:Step7RepoRootNotFound', ...
        'Could not locate the repository root for Step 7. Run the section from inside the repository.');
end

addpath(genpath(step7_repo_root));
cd(step7_repo_root);
% If step 6 ran before promoted-summary support was added, rerender it with:
% writeInitSocPromotedSummary( ...
%     fullfile(BundleEvalHelpers.resolveBundleRepoRoot(), 'Evaluation', 'initSOCs', 'results', 'atl20_p25_bundle_init_soc_sweep.mat'), ...
%     fullfile(BundleEvalHelpers.resolveBundleRepoRoot(), 'Evaluation', 'initSOCs', 'results', 'atl20_p25_bundle_init_soc_sweep_summary.mat'), ...
%     fullfile(BundleEvalHelpers.resolveBundleRepoRoot(), 'results', 'evaluation', 'desktop_atl20_bss_v1', 'evaluation__desktop_atl20_bss_v1__atl20_p25_bundle_init_soc_sweep__summary.json'), ...
%     fullfile(BundleEvalHelpers.resolveBundleRepoRoot(), 'results', 'evaluation', 'desktop_atl20_bss_v1', 'evaluation__desktop_atl20_bss_v1__atl20_p25_bundle_init_soc_sweep__summary.md'), ...
%     'desktop_atl20_bss_v1', 'atl20_p25_bundle_init_soc_sweep');
step7_bundle_name = 'atl20_p25_bundle_injection_study';
step7_suite_version = 'desktop_atl20_bss_v1';
step7_autotuning_profile_file = fullfile( ...
    step7_repo_root, 'autotuning', 'results', 'atl20_p25_bundle_autotuning_results.mat');
step7_tuned_params_file = fullfile( ...
    step7_repo_root, BundleEvalHelpers.buildPromotedParamsPath(step7_suite_version, 'atl20_p25_bundle'));
step7_results_root = fullfile( ...
    step7_repo_root, 'Evaluation', 'Injection', 'results', step7_bundle_name);
step7_aggregate_results_file = fullfile( ...
    step7_repo_root, 'Evaluation', 'Injection', 'results', ...
    'atl20_p25_bundle_injection_study.mat');
step7_summary_paths = BundleEvalHelpers.buildPromotedSummaryPaths( ...
    'evaluation', step7_suite_version, step7_bundle_name);
step7_summary_json_file = fullfile(step7_repo_root, step7_summary_paths.json_file);
step7_summary_md_file = fullfile(step7_repo_root, step7_summary_paths.markdown_file);
step7_tuning_spec = BundleEvalHelpers.resolveStep4TuningSpec( ...
    step7_autotuning_profile_file, step7_tuned_params_file, 'atl20_p25_bss_esc');
step7_noise_case = struct( ...
    'name', 'additive_measurement_noise', ...
    'mode', 'additive_measurement_noise', ...
    'dataset_family', 'additive_measurement_noise', ...
    'augmentation_type', 'additive_measurement_noise', ...
    'case_id', 'case_001', ...
    'voltage_std_mv', 15, ...
    'current_error_percent', 5, ...
    'random_seed', 7, ...
    'overwrite', false);
step7_fault_case = struct( ...
    'name', 'sensor_gain_bias_fault', ...
    'mode', 'sensor_gain_bias_fault', ...
    'dataset_family', 'sensor_gain_bias_fault', ...
    'augmentation_type', 'sensor_gain_bias_fault', ...
    'case_id', 'case_002', ...
    'current_gain', 1.1, ...
    'current_offset_a', 0.1, ...
    'voltage_gain_fault', 6e-4, ...
    'voltage_offset_mv', 2, ...
    'random_seed', 11, ...
    'overwrite', false);
step7_hall_bias_case = struct( ...
    'name', 'hall_bias', ...
    'mode', 'composite_measurement_error', ...
    'dataset_family', 'composite_measurement_error', ...
    'augmentation_type', 'composite_measurement_error', ...
    'case_id', 'case_003', ...
    'current_gain_error', 0, ...
    'current_bias_mode', 'constant', ...
    'current_bias_spec', 'c_rate_scaled', ...
    'current_bias_c_rate', -0.1, ...
    'current_noise_std_a', 0, ...
    'current_quant_lsb_a', 0, ...
    'random_seed', [], ...
    'overwrite', false);
step7_injection_cases = BundleEvalHelpers.combineInjectionCases( ...
    step7_noise_case, step7_fault_case, step7_hall_bias_case);
step7_save_summary_artifacts = true;
% Recovery-only rerender path, no injection rerun:
% writeInjectionPromotedSummary( ...
%     step7_aggregate_results_file, step7_summary_json_file, ...
%     step7_summary_md_file, step7_suite_version, step7_bundle_name);
step7_cfg = struct();
step7_cfg.run_name = step7_bundle_name;
step7_cfg.parallel = struct('use_parallel', true, 'auto_start_pool', true, 'pool_size', []);
step7_cfg.validation = struct('run_validation', true, 'show_plots', false);
step7_cfg.output = struct( ...
    'save_results', true, ...
    'results_root', step7_results_root, ...
    'datasets_root', fullfile(step7_repo_root, 'data', 'evaluation', 'derived'), ...
    'aggregate_results_file', step7_aggregate_results_file);
step7_cfg.scenarios = struct( ...
    'name', 'atl20_p25_injection', ...
    'suite_version', step7_suite_version, ...
    'source_dataset', struct( ...
        'dataset_file', fullfile(step7_repo_root, 'data', 'evaluation', 'processed', ...
            'desktop_atl20_bss_v1', 'nominal', 'esc_bus_coreBattery_dataset.mat'), ...
        'dataset_variable', 'dataset', ...
        'rebuild_dataset', false), ...
    'benchmark_dataset_template', struct( ...
        'dataset_variable', 'dataset', ...
        'dataset_soc_field', 'soc_true', ...
        'metric_soc_field', 'soc_true', ...
        'metric_voltage_field', 'voltage_v_true', ...
        'reference_name', 'Degraded SOC', ...
        'voltage_name', 'Injected voltage', ...
        'title_prefix', 'ATL20 P25 Injection'), ...
    'modelSpec', struct( ...
        'esc_model_file', fullfile(step7_repo_root, 'models', 'ATL20model_P25.mat'), ...
        'rom_model_file', fullfile(step7_repo_root, 'models', 'ROM_ATL20_beta.mat'), ...
        'tc', 25, ...
        'chemistry_label', 'ATL20', ...
        'require_rom_match', true), ...
    'estimatorSetSpec', struct( ...
        'registry_name', 'mainEval10', ...
        'allow_rom_skip', true, ...
        'tuning', step7_tuning_spec), ...
    'benchmarkFlags', struct( ...
        'SOCfigs', false, ...
        'Vfigs', false, ...
        'Biasfigs', false, ...
        'R0figs', false, ...
        'InnovationACFPACFfigs', false, ...
        'Summaryfigs', false, ...
        'Verbose', false, ...
        'use_parallel', true, ...
        'SaveResults', true, ...
        'results_file', ''), ...
    'injection_cases', step7_injection_cases);

step7_injection_results = runInjectionStudy(step7_cfg); %#ok<NASGU>
printInjectionSummary(step7_injection_results);
if step7_save_summary_artifacts
    writeInjectionPromotedSummary( ...
        step7_aggregate_results_file, step7_summary_json_file, ...
        step7_summary_md_file, step7_suite_version, step7_bundle_name);
end
