%% desktop_atl20_bss_v1
% Canonical editable workflow skeleton for the ATL desktop suite.
%
% This script is intentionally thin. Each stage calls an existing stable
% entry point and exposes the key configuration surfaces that users usually
% swap when adapting the desktop workflow.

%% Setup / addpath
repo_root = resolveWorkflowRepoRoot();
addpath(genpath(repo_root));
cd(repo_root);

%% Workflow toggles
% Enable only the stages you want to run. The default state is safe: it
% resolves the canonical paths and prints the workflow surface without
% launching long-running studies.
run_ocv_identification = false;
run_dynamic_identification = false;
run_model_validation = false;
rebuild_evaluation_suite = false;
run_autotuning_stage = false;
run_benchmark_stage = false;
run_noise_sweep_shared_stage = false;
run_noise_sweep_tuned_reference_stage = false;
run_init_soc_tuned_stage = false;
run_init_soc_shared_stage = false;
run_injection_tuned_stage = false;
run_injection_shared_stage = false;

%% Modelling inputs
workflow_name = 'desktop_atl20_bss_v1';
suite_version = 'desktop_atl20_bss_v1';

raw_evaluation_profile = fullfile( ...
    'data', 'evaluation', 'raw', 'omtlife8ahc_hp', 'Bus_CoreBatteryData_Data.mat');
canonical_evaluation_dataset = fullfile( ...
    'data', 'evaluation', 'processed', 'desktop_atl20_bss_v1', ...
    'nominal', 'esc_bus_coreBattery_dataset.mat');

ocv_data_input = fullfile('data', 'modelling', 'processed', 'ocv', 'atl20');
dynamic_data_input = fullfile('data', 'modelling', 'processed', 'dynamic', 'atl20');

% Current released desktop bundle inputs.
released_esc_model_file = fullfile('models', 'ATLmodel.mat');
active_esc_model_file = released_esc_model_file;
active_rom_model_file = fullfile('models', 'ROM_ATL20_beta.mat');

% Candidate outputs for a new identification run. Keep these separate from
% the released bundle until you decide to promote them.
ocv_model_candidate_file = fullfile( ...
    'data', 'modelling', 'derived', 'ocv_models', ...
    'atl20', 'ATLmodel-ocv-middleCurve.mat');
ocv_results_file = fullfile( ...
    'data', 'modelling', 'derived', 'identification_results', ...
    'atl20', 'ATLmodel_ocv_identification_results.mat');
esc_model_candidate_file = fullfile('models', 'ATLmodel_candidate.mat');
esc_identification_results_file = fullfile( ...
    'data', 'modelling', 'derived', 'identification_results', ...
    'atl20', 'ATLmodel_candidate_identification_results.mat');
esc_validation_results_file = fullfile( ...
    'data', 'modelling', 'derived', 'validation_results', 'esc', ...
    'ATLmodel_candidate_desktop_atl20_bss_v1_validation.mat');

% Change these when you want to benchmark a new candidate instead of the
% current released model.
benchmark_esc_model_file = active_esc_model_file;
benchmark_rom_model_file = active_rom_model_file;

bundle_estimator_names = { ...
    'ROM-EKF', ...
    'ESC-SPKF', ...
    'ESC-EKF', ...
    'EaEKF', ...
    'EacrSPKF', ...
    'EnacrSPKF', ...
    'EDUKF', ...
    'EsSPKF', ...
    'EbSPKF', ...
    'EBiSPKF', ...
    'Em7SPKF'};

%% OCV identification config
% Customize here when you want to change the OCV engine or modelling data.
% The canonical skeleton uses all available temperatures by default.
cfg_ocv = struct();
cfg_ocv.run_name = 'desktop_atl20_bss_v1_ocv_identification';
cfg_ocv.ocv_data_input = ocv_data_input;
cfg_ocv.data_prefix = 'ATL';
cfg_ocv.cell_id = 'ATL20';
cfg_ocv.engine = 'middleCurve';
cfg_ocv.temperature_scope = 'all';
cfg_ocv.desired_temperature = [];
cfg_ocv.reference_ocv_method = 'middleCurve';
cfg_ocv.save_plots = false;
cfg_ocv.debug_plots = false;
cfg_ocv.output = struct( ...
    'save_model', true, ...
    'save_results', true, ...
    'include_model_struct', false, ...
    'model_output_file', ocv_model_candidate_file, ...
    'results_file', ocv_results_file);

%% Dynamic identification config
% Swap cfg_dyn.ocv_model_input or cfg_dyn.dynamic_input when you change the
% modelling technique inputs. An empty desired_temperature keeps all
% available dynamic datasets instead of filtering to one temperature.
cfg_dyn = struct();
cfg_dyn.run_name = 'desktop_atl20_bss_v1_dynamic_identification';
cfg_dyn.ocv_model_input = ocv_model_candidate_file;
cfg_dyn.dynamic_input = dynamic_data_input;
cfg_dyn.desired_temperature = [];
cfg_dyn.numpoles = 2;
cfg_dyn.do_hysteresis = true;
cfg_dyn.output = struct( ...
    'save_model', true, ...
    'save_results', true, ...
    'enabled_plots', false, ...
    'include_model_struct', false, ...
    'model_output_file', esc_model_candidate_file, ...
    'results_file', esc_identification_results_file);

%% Model validation config
% By default validation points at the current released model. To validate a
% newly identified candidate, set validation_model_file to
% esc_model_candidate_file after running the dynamic-identification stage.
validation_model_file = benchmark_esc_model_file;
validation_dataset_file = canonical_evaluation_dataset;
validation_enable_plots = false;

%% Evaluation suite resolution
% Keep the canonical processed suite by default. Enable
% rebuild_evaluation_suite only when you intentionally want to rebuild the
% processed evaluation dataset from the raw profile and the active ESC
% model.
evaluation_builder_cfg = struct( ...
    'model_file', benchmark_esc_model_file, ...
    'profile_file', raw_evaluation_profile, ...
    'tc', 25);

datasetSpec = struct( ...
    'dataset_file', canonical_evaluation_dataset, ...
    'dataset_variable', 'dataset', ...
    'builder_fcn', 'BSSsimESCdata', ...
    'builder_cfg', evaluation_builder_cfg, ...
    'dataset_soc_field', 'soc_true', ...
    'metric_soc_field', 'soc_true', ...
    'metric_voltage_field', 'voltage_v', ...
    'reference_name', 'ESC reference', ...
    'voltage_name', 'ESC voltage', ...
    'title_prefix', 'ATL desktop');

%% Autotuning config
% Swap estimator names, datasetSpec, or modelSpec here when you want a
% different evaluation suite, model, or estimator registry.
autotuning_results_file = fullfile( ...
    'autotuning', 'results', 'desktop_atl20_bss_v1_autotuning_results.mat');

cfg_autotuning = defaultAutotuningConfig();
cfg_autotuning.run_name = 'desktop_atl20_bss_v1_autotuning';
cfg_autotuning.output.aggregate_results_file = autotuning_results_file;
cfg_autotuning.scenarios = struct( ...
    'name', 'desktop_atl20_bss_v1', ...
    'suite_version', suite_version, ...
    'estimator_names', {bundle_estimator_names}, ...
    'datasetSpec', datasetSpec, ...
    'modelSpec', struct( ...
        'esc_model_file', benchmark_esc_model_file, ...
        'rom_model_file', benchmark_rom_model_file, ...
        'tc', 25, ...
        'chemistry_label', 'ATL', ...
        'require_rom_match', true), ...
    'estimatorSetSpecBase', struct( ...
        'registry_name', 'all', ...
        'allow_rom_skip', true, ...
        'soc0_percent', [], ...
        'tuning', struct()), ...
    'objectiveFlags', struct( ...
        'SOCfigs', false, ...
        'Vfigs', false, ...
        'Biasfigs', false, ...
        'R0figs', false, ...
        'InnovationACFPACFfigs', false, ...
        'Summaryfigs', false, ...
        'Verbose', false, ...
        'SaveResults', false), ...
    'bestResultFlags', struct( ...
        'SOCfigs', false, ...
        'Vfigs', false, ...
        'Biasfigs', false, ...
        'R0figs', false, ...
        'InnovationACFPACFfigs', false, ...
        'Summaryfigs', false, ...
        'Verbose', false, ...
        'SaveResults', true, ...
        'results_file', ''));

%% Benchmark config
% Change estimatorSetSpec.registry_name or estimatorSetSpec.tuning when you
% want a different estimator registry or a tuned parameter source.
benchmark_results_file = fullfile( ...
    'Evaluation', 'results', 'desktop_atl20_bss_v1_benchmark_results.mat');

modelSpec = struct( ...
    'esc_model_file', benchmark_esc_model_file, ...
    'rom_model_file', benchmark_rom_model_file, ...
    'tc', 25, ...
    'chemistry_label', 'ATL', ...
    'require_rom_match', true);

estimatorSetSpec = struct( ...
    'registry_name', 'mainEval10', ...
    'tuning', struct());

benchmark_flags = struct( ...
    'SOCfigs', false, ...
    'Vfigs', false, ...
    'Biasfigs', false, ...
    'R0figs', false, ...
    'InnovationACFPACFfigs', false, ...
    'Summaryfigs', true, ...
    'Verbose', true, ...
    'use_parallel', true, ...
    'SaveResults', true, ...
    'results_file', benchmark_results_file);

%% Robustness study config
% The canonical surface exposes tuned-profile and shared/default variants
% for init-SOC and injection studies. The noise-sweep layer is already a
% covariance study, so the meaningful switch there is whether you keep the
% default non-swept settings or supply a tuned-reference tuning struct for
% the non-swept covariance terms.
autotuning_profile_spec = struct( ...
    'kind', 'autotuning_profile', ...
    'param_file', autotuning_results_file, ...
    'scenario_name', 'desktop_atl20_bss_v1', ...
    'selection_policy', 'best_objective', ...
    'fallback_to_default', true);

default_injection_cfg = defaultInjectionConfig();
base_injection_scenario = struct( ...
    'name', 'desktop_atl20_bss_v1', ...
    'suite_version', suite_version, ...
    'source_dataset', struct( ...
        'dataset_file', canonical_evaluation_dataset, ...
        'dataset_variable', 'dataset', ...
        'builder_fcn', 'BSSsimESCdata', ...
        'builder_cfg', evaluation_builder_cfg, ...
        'rebuild_dataset', false), ...
    'benchmark_dataset_template', struct( ...
        'dataset_variable', 'dataset', ...
        'dataset_soc_field', 'soc_true', ...
        'metric_soc_field', 'soc_true', ...
        'metric_voltage_field', 'voltage_v_true', ...
        'reference_name', 'Degraded SOC', ...
        'voltage_name', 'Injected voltage', ...
        'title_prefix', 'ATL desktop injection'), ...
    'modelSpec', modelSpec, ...
    'benchmarkFlags', struct( ...
        'SOCfigs', false, ...
        'Vfigs', false, ...
        'Biasfigs', false, ...
        'R0figs', false, ...
        'InnovationACFPACFfigs', false, ...
        'Summaryfigs', false, ...
        'Verbose', false, ...
        'use_parallel', true, ...
        'SaveResults', true, ...
        'results_file', ''), ...
    'injection_cases', default_injection_cfg.scenarios(1).injection_cases);

init_soc_range_percent = [0 100];
init_soc_step_percent = 10;

init_soc_cfg_tuned = struct();
init_soc_cfg_tuned.dataset_mode = 'esc';
init_soc_cfg_tuned.esc_dataset_file = canonical_evaluation_dataset;
init_soc_cfg_tuned.esc_model_file = benchmark_esc_model_file;
init_soc_cfg_tuned.rom_file = benchmark_rom_model_file;
init_soc_cfg_tuned.parallel = struct('use_parallel', true, 'auto_start_pool', true, 'pool_size', []);
init_soc_cfg_tuned.estimatorSetSpec = struct( ...
    'registry_name', estimatorSetSpec.registry_name, ...
    'tuning', autotuning_profile_spec);

init_soc_cfg_shared = struct();
init_soc_cfg_shared.dataset_mode = 'esc';
init_soc_cfg_shared.esc_dataset_file = canonical_evaluation_dataset;
init_soc_cfg_shared.esc_model_file = benchmark_esc_model_file;
init_soc_cfg_shared.rom_file = benchmark_rom_model_file;
init_soc_cfg_shared.parallel = struct('use_parallel', true, 'auto_start_pool', true, 'pool_size', []);
init_soc_cfg_shared.estimatorSetSpec = struct( ...
    'registry_name', estimatorSetSpec.registry_name, ...
    'tuning', struct());

noise_sigma_w_range = [1e-3 1e2];
noise_sigma_v_range = [1e-6 2e-1];
noise_step_multiplier = 5;

noise_cfg_shared = struct();
noise_cfg_shared.dataset_mode = 'esc';
noise_cfg_shared.esc_dataset_file = canonical_evaluation_dataset;
noise_cfg_shared.esc_model_file = benchmark_esc_model_file;
noise_cfg_shared.rom_file = benchmark_rom_model_file;
noise_cfg_shared.estimator_names = bundle_estimator_names;
noise_cfg_shared.use_parallel = true;
noise_cfg_shared.NoiseSummaryfigs = false;
noise_cfg_shared.PlotSocRmsefigs = false;
noise_cfg_shared.PlotVoltageRmsefigs = false;
noise_cfg_shared.tuning = struct();

noise_cfg_tuned_reference = noise_cfg_shared;
noise_cfg_tuned_reference.tuning = struct( ...
    'SigmaX0_rc', 1e-6, ...
    'SigmaX0_hk', 1e-6, ...
    'SigmaX0_soc', 1e-3, ...
    'sigma_x0_rom_tail', 2e6, ...
    'nx_rom', 12, ...
    'SigmaR0', 1e-6, ...
    'SigmaWR0', 1e-16, ...
    'current_bias_var0', 1e-5, ...
    'single_bias_process_var', 1e-8);

injection_cfg_tuned = defaultInjectionConfig();
injection_cfg_tuned.run_name = 'desktop_atl20_bss_v1_injection_tuned';
injection_cfg_tuned.parallel = struct('use_parallel', true, 'auto_start_pool', true, 'pool_size', []);
injection_cfg_tuned.validation = struct('run_validation', true, 'show_plots', false);
injection_cfg_tuned.scenarios = base_injection_scenario;
injection_cfg_tuned.scenarios.estimatorSetSpec = struct( ...
    'registry_name', 'mainEval10', ...
    'allow_rom_skip', true, ...
    'tuning', autotuning_profile_spec);

injection_cfg_shared = defaultInjectionConfig();
injection_cfg_shared.run_name = 'desktop_atl20_bss_v1_injection_shared';
injection_cfg_shared.parallel = struct('use_parallel', true, 'auto_start_pool', true, 'pool_size', []);
injection_cfg_shared.validation = struct('run_validation', true, 'show_plots', false);
injection_cfg_shared.scenarios = base_injection_scenario;
injection_cfg_shared.scenarios.estimatorSetSpec = struct( ...
    'registry_name', 'mainEval10', ...
    'allow_rom_skip', true, ...
    'tuning', struct());

%% Stage execution
ocv_results = [];
dynamic_results = [];
validation_results = [];
autotuning_results = [];
benchmark_results = [];
noise_sweep_shared_results = [];
noise_sweep_tuned_reference_results = [];
init_soc_tuned_results = [];
init_soc_shared_results = [];
injection_tuned_results = [];
injection_shared_results = [];

if run_ocv_identification
    ocv_results = runOcvIdentification(cfg_ocv);
end

if run_dynamic_identification
    dynamic_results = runDynamicIdentification(cfg_dyn);
end

if run_model_validation
    validation_results = ESCvalidation( ...
        validation_model_file, validation_dataset_file, validation_enable_plots);
    ensureParentDir(esc_validation_results_file);
    save(esc_validation_results_file, 'validation_results');
end

if rebuild_evaluation_suite
    BSSsimESCdata(canonical_evaluation_dataset, evaluation_builder_cfg);
end

if run_autotuning_stage
    autotuning_results = runAutotuning(cfg_autotuning);
end

if run_benchmark_stage
    benchmark_results = runBenchmark( ...
        datasetSpec, modelSpec, estimatorSetSpec, benchmark_flags);
end

if run_noise_sweep_shared_stage
    noise_sweep_shared_results = sweepNoiseStudy( ...
        noise_sigma_w_range, noise_sigma_v_range, noise_step_multiplier, noise_cfg_shared);
end

if run_noise_sweep_tuned_reference_stage
    noise_sweep_tuned_reference_results = sweepNoiseStudy( ...
        noise_sigma_w_range, noise_sigma_v_range, noise_step_multiplier, noise_cfg_tuned_reference);
end

if run_init_soc_tuned_stage
    init_soc_tuned_results = runInitSocStudy( ...
        init_soc_range_percent, init_soc_step_percent, init_soc_cfg_tuned);
end

if run_init_soc_shared_stage
    init_soc_shared_results = runInitSocStudy( ...
        init_soc_range_percent, init_soc_step_percent, init_soc_cfg_shared);
end

if run_injection_tuned_stage
    injection_tuned_results = runInjectionStudy(injection_cfg_tuned);
end

if run_injection_shared_stage
    injection_shared_results = runInjectionStudy(injection_cfg_shared);
end

%% Final summary / promoted outputs
summary = struct();
summary.workflow_name = workflow_name;
summary.canonical_evaluation_dataset = canonical_evaluation_dataset;
summary.released_esc_model_file = released_esc_model_file;
summary.active_benchmark_esc_model_file = benchmark_esc_model_file;
summary.active_benchmark_rom_model_file = benchmark_rom_model_file;
summary.robustness_modes = struct( ...
    'noise_sweep_shared_stage', run_noise_sweep_shared_stage, ...
    'noise_sweep_tuned_reference_stage', run_noise_sweep_tuned_reference_stage, ...
    'init_soc_tuned_stage', run_init_soc_tuned_stage, ...
    'init_soc_shared_stage', run_init_soc_shared_stage, ...
    'injection_tuned_stage', run_injection_tuned_stage, ...
    'injection_shared_stage', run_injection_shared_stage);
summary.current_selection_note = fullfile('results', 'EstimatorSelection.md');
summary.promoted_outputs = { ...
    fullfile('results', 'autotuning', suite_version), ...
    fullfile('results', 'evaluation', suite_version), ...
    fullfile('results', 'EstimatorSelection.md')};

disp(summary);

if ~isempty(ocv_results)
    fprintf('OCV identification completed: %s\n', cfg_ocv.output.model_output_file);
end
if ~isempty(dynamic_results)
    fprintf('Dynamic identification completed: %s\n', cfg_dyn.output.model_output_file);
end
if ~isempty(validation_results)
    fprintf('Model validation completed: %s\n', esc_validation_results_file);
end
if ~isempty(autotuning_results)
    fprintf('Autotuning completed: %s\n', autotuning_results_file);
end
if ~isempty(benchmark_results)
    fprintf('Benchmark completed: %s\n', benchmark_results_file);
end
if ~isempty(noise_sweep_shared_results)
    fprintf('Shared/default noise sweep completed under Evaluation/NoiseTuningSweep/results/.\n');
end
if ~isempty(noise_sweep_tuned_reference_results)
    fprintf('Tuned-reference noise sweep completed under Evaluation/NoiseTuningSweep/results/.\n');
end
if ~isempty(init_soc_tuned_results)
    fprintf('Tuned-profile init-SOC study completed under Evaluation/initSOCs/results/.\n');
end
if ~isempty(init_soc_shared_results)
    fprintf('Shared/default init-SOC study completed under Evaluation/initSOCs/results/.\n');
end
if ~isempty(injection_tuned_results)
    fprintf('Tuned-profile injection study completed under Evaluation/Injection/results/.\n');
end
if ~isempty(injection_shared_results)
    fprintf('Shared/default injection study completed under Evaluation/Injection/results/.\n');
end

fprintf(['Selection is currently documented in results/EstimatorSelection.md. ', ...
    'A formal Pareto-front artifact is still to be implemented.\n']);

function repo_root = resolveWorkflowRepoRoot()
here = fileparts(mfilename('fullpath'));
repo_root = fileparts(here);
if exist(fullfile(repo_root, 'README.md'), 'file') ~= 2 || ...
        exist(fullfile(repo_root, 'Evaluation'), 'dir') ~= 7 || ...
        exist(fullfile(repo_root, 'models'), 'dir') ~= 7
    error('desktop_atl20_bss_v1:RepoRootNotFound', ...
        'Could not resolve the repository root from workflows/desktop_atl20_bss_v1.m.');
end
end

function ensureParentDir(file_path)
parent_dir = fileparts(file_path);
if ~isempty(parent_dir) && exist(parent_dir, 'dir') ~= 7
    mkdir(parent_dir);
end
end
