function artifact = writeOcvInspectionArtifacts(inspection)
% writeOcvInspectionArtifacts Write promoted JSON and Markdown summaries for an OCV inspection run.

if nargin < 1 || isempty(inspection)
    error('writeOcvInspectionArtifacts:MissingInspection', ...
        'inspection is required.');
end

paths = resolveOcvInspectionPaths(inspection.config);
artifact = buildArtifact(inspection, paths);
markdown_text = renderMarkdown(artifact);

BundleEvalHelpers.writeJsonArtifact(paths.summary_json_abs, artifact);
BundleEvalHelpers.writeMarkdownArtifact(paths.summary_markdown_abs, markdown_text);
end

function artifact = buildArtifact(inspection, paths)
selected_method = summarizeSelectedMethod(fieldOr(inspection, 'selected_method', struct()));
method_rows = summarizeMethods(inspection.methods, selected_method);
method_details = summarizeMethodDetails(inspection.methods);
data_files = summarizeDataFiles(inspection.data, paths.repo_root);
figure_rows = summarizeFigures(fieldOr(inspection, 'visual_inspection', struct()));

artifact = struct();
artifact.artifact_class = 'summary';
artifact.kind = 'ocv_inspection_summary';
artifact.layer = 'ocv';
artifact.created_on = char(datetime('now', 'TimeZone', 'local', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ssXXX'));
artifact.suite_version = paths.suite_version;
artifact.scenario_id = paths.scenario_id;
artifact.summary_json_file = BundleEvalHelpers.normalizeStoredPath(paths.summary_json_abs);
artifact.summary_markdown_file = BundleEvalHelpers.normalizeStoredPath(paths.summary_markdown_abs);
artifact.figure_root = BundleEvalHelpers.normalizeStoredPath(paths.figure_root_abs);
artifact.reference_metrics_note = ['Reference metrics are method-relative metrics computed against ' ...
    'a reconstructed OCV reference (middleCurve by default). They are not ' ...
    'absolute physical-ground-truth OCV error metrics.'];
artifact.selected_method = selected_method;
artifact.reference_method = struct( ...
    'ocv_method', char(fieldOr(inspection.reference, 'ocv_method', 'middleCurve')), ...
    'description', 'Method-relative reconstructed OCV used to score the candidate models.');
artifact.input = struct( ...
    'cell_id', char(fieldOr(inspection.config, 'cell_id', '')), ...
    'data_prefix', char(fieldOr(inspection.config, 'data_prefix', '')), ...
    'ocv_data_input', normalizeStoredInput(fieldOr(inspection.config, 'ocv_data_input', ''), paths.repo_root), ...
    'temperature_scope_degC', reshape(fieldOr(inspection, 'temps_degC', []), 1, []), ...
    'data_files', data_files);
artifact.config = sanitizeConfig(fieldOr(inspection, 'config', struct()), paths.repo_root);
artifact.methods = method_rows;
artifact.method_details = method_details;
artifact.saved_figures = figure_rows;
artifact.rerun = buildRerunMetadata(artifact.input, artifact.config);
end

function markdown_text = renderMarkdown(artifact)
lines = { ...
    '# OCV Modelling Inspection Summary'; ...
    ''; ...
    sprintf('- layer: `%s`', artifact.layer); ...
    sprintf('- suite: `%s`', artifact.suite_version); ...
    sprintf('- scenario: `%s`', artifact.scenario_id); ...
    sprintf('- generated: `%s`', artifact.created_on); ...
    sprintf('- promoted JSON: `%s`', artifact.summary_json_file); ...
    sprintf('- promoted Markdown: `%s`', artifact.summary_markdown_file); ...
    sprintf('- figure root: `%s`', artifact.figure_root); ...
    ''; ...
    '## Decision Record'; ...
    ''; ...
    sprintf('- selected/default method: `%s`', artifact.selected_method.display_name); ...
    sprintf('- engine: `%s`', artifact.selected_method.engine); ...
    sprintf('- diag type: `%s`', fallbackText(artifact.selected_method.diag_type, 'n/a')); ...
    sprintf('- selection source: `%s`', artifact.selected_method.selection_source); ...
    sprintf('- rationale: %s', artifact.selected_method.rationale); ...
    ''; ...
    '## Reference Metrics Note'; ...
    ''; ...
    artifact.reference_metrics_note; ...
    sprintf('- metrics reference method: `%s`', artifact.reference_method.ocv_method); ...
    ''; ...
    '## Inputs'; ...
    ''; ...
    sprintf('- cell id: `%s`', artifact.input.cell_id); ...
    sprintf('- data prefix: `%s`', artifact.input.data_prefix); ...
    sprintf('- OCV data input: `%s`', artifact.input.ocv_data_input); ...
    sprintf('- temperatures (degC): `%s`', mat2str(artifact.input.temperature_scope_degC)); ...
    ''};

if ~isempty(artifact.input.data_files)
    lines = BundleEvalHelpers.appendMarkdownLines(lines, {'### Dataset Files'; ''});
    lines = BundleEvalHelpers.appendMarkdownLines(lines, BundleEvalHelpers.markdownTableFromStructArray(artifact.input.data_files));
    lines = BundleEvalHelpers.appendMarkdownLines(lines, {''});
end

lines = BundleEvalHelpers.appendMarkdownLines(lines, {'## Evaluated Methods'; ''});
lines = BundleEvalHelpers.appendMarkdownLines(lines, BundleEvalHelpers.markdownTableFromStructArray(artifact.methods));
lines = BundleEvalHelpers.appendMarkdownLines(lines, {''; '## Saved Figures'; ''});
lines = BundleEvalHelpers.appendMarkdownLines(lines, BundleEvalHelpers.markdownTableFromStructArray(artifact.saved_figures));
lines = BundleEvalHelpers.appendMarkdownLines(lines, {''; '## Reproducibility'; ''});
lines = BundleEvalHelpers.appendMarkdownLines(lines, { ...
    'Run the default inspection workflow with:', ...
    '', ...
    '```matlab', ...
    'addpath(genpath(''.''));', ...
    'run(fullfile(''ocv_id'', ''stdy'', ''runOcvModellingInspection.m''));', ...
    '```', ...
    '', ...
    'The run recorded this effective configuration:', ...
    '', ...
    sprintf('- `ocv_data_input`: `%s`', artifact.config.ocv_data_input), ...
    sprintf('- `data_prefix`: `%s`', artifact.config.data_prefix), ...
    sprintf('- `cell_id`: `%s`', artifact.config.cell_id), ...
    sprintf('- `desired_temperatures`: `%s`', mat2str(artifact.config.desired_temperatures)), ...
    sprintf('- `reference_ocv_method`: `%s`', artifact.config.reference_ocv_method), ...
    sprintf('- `plot_diag_methods`: `%s`', logicalText(artifact.config.plot_diag_methods)), ...
    sprintf('- `save_inspection_figures`: `%s`', logicalText(artifact.config.save_inspection_figures)), ...
    sprintf('- `inspection_figure_format`: `%s`', artifact.config.inspection_figure_format), ...
    sprintf('- `selected_method`: `%s`', fallbackText(artifact.config.selected_method, '[default middleCurve]')), ...
    ''});

markdown_text = strjoin(lines, newline);
end

function rows = summarizeMethods(methods, selected_method)
if isempty(methods)
    rows = struct([]);
    return;
end

rows = repmat(struct( ...
    'rank', NaN, ...
    'selected', false, ...
    'display_name', '', ...
    'engine', '', ...
    'diag_type', '', ...
    'plot_enabled', false, ...
    'mean_rmse_mv', NaN, ...
    'max_rmse_mv', NaN, ...
    'mean_error_mv', NaN, ...
    'mean_mae_mv', NaN, ...
    'max_abs_error_mv', NaN, ...
    'case_count', NaN), numel(methods), 1);

for idx = 1:numel(methods)
    metrics = fieldOr(methods(idx), 'metrics', struct());
    rows(idx).display_name = char(fieldOr(methods(idx), 'display_name', ''));
    rows(idx).engine = char(fieldOr(methods(idx), 'engine', ''));
    rows(idx).diag_type = char(fieldOr(methods(idx), 'diag_type', ''));
    rows(idx).selected = strcmp(rows(idx).engine, selected_method.engine) && ...
        strcmp(rows(idx).diag_type, selected_method.diag_type);
    rows(idx).plot_enabled = logical(fieldOr(methods(idx), 'plot_enabled', true));
    rows(idx).mean_rmse_mv = fieldOr(metrics, 'mean_rmse_mv', NaN);
    rows(idx).max_rmse_mv = fieldOr(metrics, 'max_rmse_mv', NaN);
    rows(idx).mean_error_mv = fieldOr(metrics, 'mean_error_mv', NaN);
    rows(idx).mean_mae_mv = fieldOr(metrics, 'mean_mae_mv', NaN);
    rows(idx).max_abs_error_mv = fieldOr(metrics, 'max_abs_error_mv', NaN);
    rows(idx).case_count = fieldOr(metrics, 'case_count', NaN);
  end

[~, order] = sort([rows.mean_rmse_mv], 'ascend');
rows = rows(order);
for idx = 1:numel(rows)
    rows(idx).rank = idx;
end
end

function details = summarizeMethodDetails(methods)
if isempty(methods)
    details = struct([]);
    return;
end

details = repmat(struct( ...
    'display_name', '', ...
    'engine', '', ...
    'diag_type', '', ...
    'reference_metrics_by_temperature', struct([])), numel(methods), 1);

for idx = 1:numel(methods)
    details(idx).display_name = char(fieldOr(methods(idx), 'display_name', ''));
    details(idx).engine = char(fieldOr(methods(idx), 'engine', ''));
    details(idx).diag_type = char(fieldOr(methods(idx), 'diag_type', ''));
    summary_table = table();
    if isfield(methods(idx), 'identification_results') && ...
            isfield(methods(idx).identification_results, 'ocv_validation') && ...
            ~isempty(methods(idx).identification_results.ocv_validation.models)
        summary_table = methods(idx).identification_results.ocv_validation.models(1).summary_table;
    elseif isfield(methods(idx), 'model') && isfield(methods(idx).model, 'metrics') && ...
            isfield(methods(idx).model.metrics, 'ocv_summary_table')
        summary_table = methods(idx).model.metrics.ocv_summary_table;
    end
    details(idx).reference_metrics_by_temperature = BundleEvalHelpers.tableRows(summary_table);
end
end

function rows = summarizeDataFiles(data, repo_root)
if isempty(data)
    rows = struct([]);
    return;
end

rows = repmat(struct('temp_degC', NaN, 'source_file', ''), numel(data), 1);
for idx = 1:numel(data)
    rows(idx).temp_degC = fieldOr(data(idx), 'temp', NaN);
    rows(idx).source_file = normalizeStoredInput(fieldOr(data(idx), 'source_file', ''), repo_root);
end
end

function rows = summarizeFigures(visual_inspection)
figure_outputs = fieldOr(visual_inspection, 'figure_outputs', struct([]));
if isempty(figure_outputs)
    rows = struct('temp_degC', NaN, 'saved_figure', 'Not saved');
    return;
end

rows = repmat(struct('temp_degC', NaN, 'saved_figure', ''), numel(figure_outputs), 1);
for idx = 1:numel(figure_outputs)
    rows(idx).temp_degC = fieldOr(figure_outputs(idx), 'temp_degC', NaN);
    rows(idx).saved_figure = char(fieldOr(figure_outputs(idx), 'relative_path', ''));
end
end

function selected_method = summarizeSelectedMethod(selection)
selected_method = struct( ...
    'display_name', char(fieldOr(selection, 'display_name', 'Middle curve')), ...
    'engine', char(fieldOr(selection, 'engine', 'middleCurve')), ...
    'diag_type', char(fieldOr(selection, 'diag_type', '')), ...
    'selection_source', char(fieldOr(selection, 'selection_source', 'default')), ...
    'rationale', char(fieldOr(selection, 'rationale', ...
        'No explicit OCV method preference or visual-inspection choice was recorded; defaulted to middleCurve.')));
end

function rerun = buildRerunMetadata(input_data, cfg)
rerun = struct();
rerun.command = 'run(fullfile(''ocv_id'', ''stdy'', ''runOcvModellingInspection.m''));';
rerun.dataset = input_data.ocv_data_input;
rerun.config = cfg;
end

function cfg_out = sanitizeConfig(cfg_in, repo_root)
cfg_out = cfg_in;
cfg_out.ocv_data_input = normalizeStoredInput(fieldOr(cfg_in, 'ocv_data_input', ''), repo_root);
end

function text = logicalText(value)
text = char(string(logical(value)));
end

function text = fallbackText(value, fallback)
if isempty(value)
    text = fallback;
else
    text = char(value);
end
end

function value_out = normalizeStoredInput(value_in, repo_root)
if ischar(value_in) || (isstring(value_in) && isscalar(value_in))
    value = char(value_in);
    if ~isempty(value) && ~BundleEvalHelpers.isAbsolutePath(value)
        value = fullfile(repo_root, value);
    end
    value_out = BundleEvalHelpers.normalizeStoredPath(value);
else
    value_out = value_in;
end
end

function value = fieldOr(s, field_name, default_value)
if isstruct(s) && isfield(s, field_name) && ~isempty(s.(field_name))
    value = s.(field_name);
else
    value = default_value;
end
end
